[short="The Life and Travels of John Barcroft"]
== A Brief Account of the Life and Travels, etc. of John Barcroft

It hath often been in my mind to leave a short account to
my children of the Lord`'s gracious dealings with me,
which are as follow, viz.

I was born at Shralegh, near Rosenallies, in the Queens-County, in Ireland,
in the year 1664;
about which time (or soon after) my parents were convinced of the blessed truth.
They were born at Couln in Lancashire,
in England (descended from a family of considerable
account in the world) and came to settle in Ireland,
in, or near the year 1658.
I was the youngest child they had, and when about five years old,
I went with my mother to a meeting of the people called Quakers,
held at William Edmundson`'s house;
where through the effectual preaching of a servant of the Lord, (viz.) Samuel Thornton,
I was greatly reached, and tendered by the Lord`'s power, insomuch that I wondered at it;
and as I was going home after the meeting, told my dear mother, how I had been therein,
at which she was greatly broken into tears (to my admiration) being a worthy,
religious woman.
From this time I had a great love and esteem for the Lord`'s servants and people,
with a fear upon me, left I should offend the Lord,
after I knew it was his power that had reached unto me,
praise be given to his powerful name; who thus touched my heart when very young,
and hath been my preserver to this day.

In about the year 1673, my parents removed to Ballymorane, in the Kings-County,
where then was no meeting of Friends, but soon after,
divers Friends came to settle near Edenderry,
and the meeting was kept for some time at my father`'s house;
and being frequently visited by Friends of the ministry,
many English neighbours were invited, and came to the meetings,
where being reached by the testimony of truth declared, several of them were convinced,
and turned from the evil of their ways.
When I was sent to invite the neighbours (which was
often) I was under great fear and concern,
how to answer such who might query of me on that account (being but a child),
and the Lord often furnished me with such suitable
answers as caused both me and others to admire:
though I was not forward to argue or discourse about religion, knowing my own weakness;
but upon such occasions, cried secretly to the Lord for wisdom,
my love increasing to him and his people;
with earnest desire to be in the company of honest Friends,
whereby I found great benefit and comfort,
often marvelling that such Friends took that notice of me as they did,
particularly those of the ministry,
frequently desiring my father to let me go with them to meetings
(at some distance from ours) to which he readily consented;
for both my father and mother greatly desired my growth in the truth,
and were willing to encourage me in accompanying traveling Friends, when I was but young.

Having thus known the Lord`'s appearance in great love to my soul,
and preservation from evils, so that my conversation was orderly and blameless;
also having the love of Friends and others,
I was like to have sat down contented in this state;
but the Lord was graciously pleased to let me see this was not to be my rest,
and that I must know a new-birth, which brought great exercise upon me,
under which I cried mightily unto the Lord day and night to effect
it (being sensible I could do nothing therein of my self),
beseeching the Lord Jesus Christ to look upon me, a poor, distressed creature,
that I might know his baptism with the Holy Ghost and fire,
and thereby be made a true member of his church.
For I saw plainly,
that although I had been sprinkled with elementary water it availed me nothing;
and what I had known of the Lord`'s love was preparatory
to this great and necessary work.
So I often sought solitary places to weep in;
then came into my remembrance that saying of the apostle Paul,
viz. "`Oh wretched man that I am, who shall deliver me from the body of this death?`" Rom. 7:24.
And I thought at times,
it had been happy for me if I were as a fowl of the air, they singing but I mourning,
and was sometimes nigh to despair; yet the Lord remembered me,
mixing mercy with his judgments, and gave me hope of his salvation.
So I saw it was good for me that I had been afflicted,
and known the pain of the spiritual birth, having before been in a natural state.
I could write much concerning the Lord`'s dealings with me in such times, and hope +++[+++I]
shall never forget his heavenly hand, which wrought in me in my young days.

My parents now growing ancient, and being desirous I should marry,
that they might see me settled before their deaths,
I found my affection incline towards Elizabeth Tibbs, daughter of Henry Tibbs, deceased,
supposing her to be a religious young woman, and of a good family;
in which weighty concern I often desired the Lord to direct me;
and after having pondered it in my mind, and waited for his counsel,
I acquainted my parents (and brother then living) and by
their consent applied to her mother and step-father,
as also Anthony Sharp, he being left in trust by her own father, who all consenting,
I proceeded accordingly, and our marriage was accomplished in the year 1685.

After I was married, we dwelt some time at Ballymorane,
and had three children before we removed thence; but the war coming on,
the Irish grew very wicked, first taking up horses and arms from the Protestants,
so proceeded to plundering; and we having then a good stock,
they took away not only our horses (scarce leaving us one
to ride on) but also our other cattle and sheep,
at their pleasure; so that my wife often asked, "`Had they taken all?`"
with desire it were so, that we might be the more quiet.
In which troublesome times the Lord greatly helped us,
and I often observed his good providence;
in that I and my wife were not both cast down at once.
Thus one was made very helpful to the other.

This general calamity of this nation was often foretold and declared
of by that ancient servant of the Lord William Edmundson,
as a time that would try all our foundations; and we were tried many ways during the war.

After our stock was mostly gone, the Ulster-Irish came in great numbers,
spreading over the country like a disorderly camp,
filling our houses with their officers, without order of billets,
and many dying of a violent, mortal fever, that was amongst them, were buried in ditches;
yet in all these perilous times (except one first day of the week) we diligently
kept up and attended our religious meetings for the worship of Almighty God;
and his bowing tendering power was often eminently enjoyed,
to the comfort of our drooping spirits;
but on the said first day that we stayed from meeting (not thinking it
safe to leave our servants with that throng of Irish officers in the house,
and the camp near us) I viewed the guests as they were sitting about my table,
and the remembrance of my ancient, honourable Friends that had sat about it,
came fresh in my mind; and I cried in my heart to the Lord,
"`Shall I ever see such times again?`"
and received an answer, I should.
Then I renewed covenant with the Lord,
that if he would bring it to pass I would be devoted to serve him all my days,
according to the ability he would please to give me, which I have since often remembered,
and endeavoured thus far to perform, the Lord having greatly helped me in many exercises,
to the praise of his great name and comfort of my soul.

It being now a time of great distress and havoc, by fire and sword in these parts,
and our stock mostly gone, I found freedom to remove with my family to Dunshoughan,
four miles from Dublin, where we dwelt about nine months,
and had a good settlement and great offers, if I would continue there;
but when the war was over, I inclined to return near Edenderry,
many of our Friends that had inhabited there being dead and scattered,
and part of the town burnt, William Chandlee and his family only remained,
having lodged in his windmill the foregoing winter.
So I settled at Arkhill, and William Chandlee and I, with our families,
met together to worship God,
continuing so for some months before any more Friends joined to us; we met in faith,
that our meeting would increase, and in time it did so,
being now the largest meeting in the province of Leinster, except Dublin;
for I was earnestly concerned to help many Friends to places to dwell in,
which was an enlargement to the meeting and comfort to me;
and many heavenly comfortable seasons we have had therein,
the glory of the Lord shining clearly amongst us.
Praise be given to his great name.

In the year 1693 I had a great exercise upon me for the succeeding generation,
seeing the ancient Friends were going off, or taken away by death,
who had been good examples, and concerned for the promotion of truth in their day,
and that too many of their children did not follow their footsteps,
some going into pride, and others into sundry defilements of the world;
so that it seemed as if the Lord`'s glorious work would fall,
which deeply affected me with sorrow for some months;
and having cried unto the Lord day and night,
he was pleased to shew me in a vision as I lay on my bed,
the elders gathered on an exceeding green hill, and many of us,
who were younger standing on the hill below them,
they were earnestly concerned for us and gave us
the books of record which they had written,
with a charge that we should observe the same, and serve the Lord God,
as they had done in their day; so kneeling down they prayed to the Lord for us,
and he heard and answered them, and poured of his Spirit upon us,
as upon them at the beginning,
and many spoke of the mysteries of Christ`'s kingdom and government,
that shall never have end,
and that many should be sent forth to publish the glad tidings of the gospel of peace;
and a glorious visitation I saw, and that the Lord`'s work would prosper in the earth.
When this vision was withdrawn, I considered these things,
and my spirit was greatly overcome in the sense of God`'s goodness;
and my soul and spirit praised the Lord God and the Lamb,
who is worthy forever and ever.

About this time I had large openings, such as I never had before,
and the mysteries of the holy scriptures were revealed to me,
and I believed the Lord would call me into his ministry;
and therefore often besought him,
that he would be pleased to give me a good understanding, that I might not be deceived.

In the year 1694, I accompanied that eminent servant of the Lord William Edmundson,
into the North of Ireland, William Fayle the elder being with us,
we had many comfortable seasons, and it was a good journey to me;
I saw the great need of Friends`' care one over another, to keep things in order,
and was willing to help in this service, according to the ability given,
believing the Lord had gifted me for it, and so would have been content in this service;
but the Lord brought a further concern upon my spirit (and his word was
as a fire in me) shewing that he would send me to visit my brethren;
and that as he had visited their fathers so would he visit them,
and give unto some of us, of a younger generation, a portion of his Spirit;
and though I believed this was the word of the Lord, yet fears and jealousies seized me,
consulting what people would say if I gave up, not having such openings and revelations,
as in some time past; likewise considering, that some who had been lively,
and of large experience in the ministry, going at times beyond their gifts,
continued in words, or declaration without life,
to the hurt of themselves and the meeting they spoke to.
Thus my fears increasing, several Friends were drawn forth,
to speak to my condition in public, particularly dear Thomas Wilson;
yet I could not acquaint him of my exercise,
though I went to his house with that purpose,
neither when he came to my house some time after,
which I thought might have been a suitable opportunity.

Thus continuing under great fear and reasoning, as with flesh and blood,
the Lord withdrew from me for a season; and I sat dead and dry,
without the enjoyment of truth in our religious meetings,
and the like when out of meeting.
Then I remembered the promises that I had made to the Lord and not performed,
of giving up to his requirings, and was afraid,
as giving him just occasion to withdraw from me; so +++[+++I]
continued in a state of great mourning and bitter lamentation many days,
some of which I was forced to keep my bed;
but the Lord remembered and visited me again in mercy:
then I resolved to be more obedient for the future;
but alas! when I was tried I still found it hard to give up; for not long after,
there came a concern upon me to speak some words in the meeting;
and though I was sensible Friends were under a travail of spirit for me, I withheld long,
until the Lord`'s power was so weighty upon me, that I stood up and spoke a few words,
which mightily broke the meeting into tenderness, and I went home with comfort,
hoping to be more obedient hereafter;
yet I found it a great cross to my mind to obey when a like exercise came upon me again,
but through the Lord`'s assistance I was made willing to answer his holy requirings,
and therein found peace.
This was in the latter end of the year 1696.

In the year 1697 Roger Roberts and I went to accompany William
Edmundson and George Rooke in their travel to England.
We took shipping at Dublin, and landed at Holyhead, from whence we rode to Bangor,
and had a meeting at Clanrost, another at the house of David Jones,
and one at the house of Lewis Owens near Dolgellee,
from whence we went to Charles Loya`'s, at Doloboran, and stayed two meetings there,
and travelled thence to the yearly-meeting of Wales, held at Lanneedlass,
after which George Rooke went into South Wales, but William Edmundson,
Roger Roberts and I went to Roger Hugh`'s, and had a meeting there;
and from thence to Lemster, and stayed their meeting,
at which place William being taken unwell, tarried some time, and Roger with him,
but I went with Thomas Thompson to Worcester,
from whence I went to see some of my wife`'s relations at Birmingham and Alcester,
and thence to Glocester, expecting to meet my companions, viz. William and George,
but met only with some letters, the last whereof gave an account,
that William Edmundson was scarce expected to recover of his illness,
which caused me to hasten to Lemster, and so got thither pretty early next morning;
and there being a meeting that day at Timothy Townsen`'s,
I heard William declaring before I went in, whereat I greatly rejoiced;
yet we stayed some days ere he was able to travel;
we went from thence to Ross and so to Glocester,
where William had great service in testimony for the Lord,
being enabled to stand a long time in the meeting, and afterwards walked to his lodging,
as if he felt no weakness, saying, the Lord had healed him, and so continued hearty,
though he was scarce able to walk when he went to that meeting.

We went from Glocester to Nailsworth, where was a meeting and marriage,
and thence to the yearly-meeting at Bristol, which held four days,
where William Edmundson and George Rooke had good service,
from whence we went to Melksham, and had a large meeting, and thence to Chippenham,
and had two meetings there, so to Caln, Marlborough and Ore,
having a meeting at each place, and thence to Reading, where we had two large meetings,
and from thence to High-Wickomb; and had a meeting, so to Thomas Elwood`'s house,
and next day to their meeting at Jordan, so to the yearly-meeting at London;
throughout which journey William had great service for the Lord in doctrine and discipline,
being largely gifted for both.

After the yearly-meeting at London was over,
William Edmundson and George Rooke went towards Colchester,
but Roger Roberts and I (with Thomas Cuppage and Amos Strettel,
who had been from Ireland at the said yearly-meeting) took
leave of William and George in the tender love of God,
and set forward to Holyhead, where before we went on shipboard,
we sat down to wait on the Lord, who had been with us in our journey,
and accepted our small service, under a sense whereof,
our souls and spirits were greatly tendered and comforted, returning him the praise,
who is worthy forever.
We crossed the channel in six hours, and I got home from London in eight days,
and found my wife and children well in health,
which was cause of thankfulness to the Lord.

In the year 1698, I had a concern to visit the meetings of Friends in Munster,
though under fear to go forth in such a weighty work; but the concern remaining,
I acquainted our monthly-meeting therewith,
who gave me a certificate of their concurrence, and Richard Scott accompanied me;
we went to the province-meeting at Clonmel, and thence to John Fennel`'s,
so to the meetings of Friends in the county of Tipperary,
having the company of George Griffits from the said province-meeting:

We went from thence to Youghal and to Cork, where we I had a blessed meeting,
and thence to Bandon, and back to Cork, so to Charlevil and Limerick,
having meetings in the said places.
After which I had also a meeting at Birr,
and found great peace from the Lord in this journey, so returned home.

In the year 1699,
having a concern up on my mind to visit Friends s again in the province of Munster,
I went to Waterford, where I met with Robert Hoope, accompanied by Joshua Beale;
we went from thence to Clonmel, so to Cashel, Kilcommon, Youghal, Cork, Bandon,
Charlevil, Limerick and Birr, and had many comfortable meetings,
the Lord`'s presence being with us.
So having had good satisfaction in the company one of another,
we parted in great love and tenderness, Robert went towards the Moate Granogue,
and I returned home.

In the year 1700,
I had drawings on on my mind to go to the yearly meeting at London
and visit Friends`' meetings in some other parts of England,
but was attended with fear of undertaking so weighty a service, knowing my own weakness;
yet the exercise continuing heavy upon me for some months, I often cried to the Lord,
that he would be pleased to remove it,
and lay the concern upon one more fit for the service, which to me appeared the harder,
in that I knew of no companion; but after I had resigned to the will of God,
about two or three days before I left home,
a concern came upon my dear Friend Thomas Wilson to go with me to London,
for which I was thankful to the Lord.

We went from the national half-year`'s meeting in Dublin,
accompanied by Samuel Randal and John Hammond, and had a ready passage,
and travelled by land to London, having but one meeting by the way, at Albans,
the time being short; we had many comfortable seasons at this yearly-meeting,
and divers brethren being there, with whom I had former acquaintance;
we were glad to see each other; but when that meeting was over,
Thomas Wilson not being clear of the city, stayed longer,
which was a renewed exercise to me;
yet in the will of God we parted for the service sake, in a great cross to our selves;
so John Gratton, Thomas Upsher and I, and some other Friends left the city,
being accompanied some miles by Samuel Waldenfield and others, who returned.
We went to the quarterly and yearly-meeting at Colchester,
where I had good service for the Lord, and to his people,
whereby I was greatly confirmed.
From thence I went to Woodbridge accompanied by Thomas Upsher,
to the quarterly and yearly-meeting, where we had a satisfactory time,
being comforted in the Lord, and one in another; Thomas Upsher left me here,
but William Fell went with me to Norridge, Lynn and other meetings there-away,
so into Lincolnshire, to Lincoln, Gainsborough, and a monthly-meeting near Brigg,
in which service the Lord was pleased to accompany us with his good presence.
Praise be given to his great name forever.
Now being clear of these parts, we went into Yorkshire, where William Fell left me.

I went to the house of our dear friend Thomas Aldam,
and thence (accompanied by his son Thomas) to Woodhouse-Meeting,
wherein the Lord`'s power appeared eminently, to the comfort of many souls;
after which I went that night, to cousin Daniel Barnard`'s, near Sheffield,
having never seen him before, and had good satisfaction in my visit,
though neither he or his family came then to Friends`' meetings;
but in some years after did join with Friends.
I returned from thence to Thomas Aldam`'s,
where I unexpectedly met with my dear Friend Thomas Wilson, to our great comfort,
acquainting each other how we had fared, with gladness and thanksgiving to the Lord God,
and the Lamb, Christ Jesus,
who had accounted us worthy to be concerned in publishing the gospel of life and salvation.

From hence we were accompanied by Thomas Aldam and other Friends,
to the quarterly and yearly-meeting at York,
wherein the Lord`'s power wonderfully appeared; it was a blessed time to many,
and Friends parted in great love and tenderness, with thankfulness to the Lord,
for his goodness extended unto us.
We went from thence to Darlington, and had two meetings there on a first day of the week,
and the Lord`'s goodness was enjoyed therein; so to the quarterly-meeting at Durham,
wherein the Lord`'s presence and power appeared amongst Friends,
etc. both in the meeting for worship, and in that for discipline;
from whence we went to Cumberland, and was at their quarterly meeting at Coldbeck;
where the Lord`'s power broke in wonderfully,
to the melting of many hearts and souls before him,
causing them to rejoice in his presence and bless his great name.
We went from thence to Penrith, and had a very large meeting in their burying-place,
the meetinghouse being too little to contain the number of people:
The gospel was published freely, and the testimony of truth set over transgressors.
We went thence to Kendal, and so to the quarterly-meeting at Lancaster,
where was a large appearance of Friends,
and the Lord`'s presence eminently manifested among us.
We went from thence to Thomas Camm`'s, and had great satisfaction there,
he and his wife being then living, and thence to the quarterly-meeting at Kendal,
where the Lord`'s goodness was enjoyed, to the rejoicing of many hearts,

Thomas Wilson returned from Kendal back to Cumberland, having drawings that way;
but I went into Lancashire, and had several good satisfactory meetings about Couln,
where my parents were born.
From thence I went to John Haydock`'s; and thence to the monthly-meeting at Hartshaw.
So finding my spirit clear of the service which had been required of me, in that nation,
and my soul greatly comforted in feeling sweet peace from the Lord;
my way then opened homeward, and I went accordingly to Chester, so to Holyhead,
and had a safe passage from thence to Dublin; from whence I got home,
and found my wife and family well, and Friends glad to see me safe returned;
everlasting praises be given to God.

Thomas Wilson got home in a few days after me, which was cause of gladness to us both,
having been about three months from home.
I had great openings in the time of this journey, both in doctrine and discipline,
the latter being greatly wanted in many places; and my spirit travailed deeply,
that good order might be set up and maintained in the church of Christ,
and disorder kept out.

Having had drawings on my mind for a considerable time to
visit the meetings of Friends in Ulster Province,
I went to the meeting at Oldcastle, and thence to Ballyhayes,
so to the province-meeting at Ballyhagan,
after which I was accompanied by Robert Robinson to Charlemont, Dunclaudy, Colerain,
James Moore`'s, Grange, Antrim, and Lurgan;
and from thence by dear Robert Hoope to Ballenderry, Lisnegarvy, and Carrickfergus;
at which place John Lauder`'s marriage was solemnized in the meeting.
In all which journey the Lord was with me, and enabled me to answer his requirings:
so that I may measurably say, though I went out weeping, bearing precious seed,
I returned home as with a sheaf in my bosom.

In the year 1700 I went again into the province of Ulster, accompanied by Gershon Boate,
the younger, and had a satisfactory journey,
in visiting all the meetings of Friends in that province,
the Lord having accompanied us with his goodness; blessed be his name forever.
At the Grange we had a very remarkable parting with James Greenwood, and his wife Ann,
which made me think I should never see them more;
and in a few months after they were both removed by death,
which is a great loss to the church.

In the year 1701,
I had great drawings on my mind to visit the meetings of Friends again in Munster Province,
and accordingly proceeded in company with Thomas Wilson to Waterford and thence to Clonmel,
Cashel, John Fennell`'s, Youghal, Cork, Bandon, Charlevil, Limerick, and so to Birr,
having meetings in the aforesaid places;
and the Lord was graciously pleased to enable us by his
Holy Spirit to perform our service in this journey,
to the comfort of many; for which mercy we were truly thankful to the Lord,
and returned home in great peace.

In the year 1702,
I found a concern upon my mind to accompany several
Friends to the yearly-meeting at London,
to join with Friends there in seeking to obtain an
affirmation that might be easy to all Friends;
George Rooke and I had a concern upon us to stay at Market-street,
on the first day of the week, and had a comfortable meeting there,
Roger Roberts being with us, the rest of our company being at Mins that day;
but we all met at London, and stayed the yearly-meeting there;
and some time after returned homeward; and at Chester, Robert Hoope, Roger Roberts,
John Pim and I, with some other Friends, had a meeting,
consisting mostly of young people (many of the elders being gone to the
monthly-meeting) and the Lord greatly refreshed our drooping spirits.
We went from thence to Holyhead, and took shipping for Ireland; concerning which journey,
I refer, for a more particular account,
to the journal of our dear Friend William Edmundson.

In the latter end of the year 1702,
I went with John Bousted of Cumberland into the province of Ulster;
we had a meeting at Oldcastle, from whence, John went to visit an acquaintance,
but I went to Ballyhayes, and had a remarkable meeting,
Friends there being under exercise about some disorders which had happened;
I met again with John Bousted, at Coothill, where we had a good meeting.
We went thence to Charlemont, and Ballyhagan, so to the province-meeting at Lurgan;
and having a great exercise upon me, Robert Hoope accompanied me thence to Rathfryland,
where we parted; but before I got home I was fully persuaded one of my children was dead,
which proved accordingly, being my daughter Elizabeth, a sober, hopeful child,
about seven years old, she was buried that day I got home.
I was some time unwell of body after this journey,
occasioned through extreme storminess of the weather, being in the eleventh month;
but when recovered +++[+++and]
able to travel, I went with dear Thomas Wilson to the province-meting of Munster,
at Clonmel.

In the year 1704, I went into Ulster Province, in company with Joshua Northal,
and visited Friends in all their meetings, having comfortable seasons with them;
the faithful gladly received our visit, and the unfaithful were exhorted to faithfulness;
we returned with great sweetness upon our spirits, and thankfulness to God,
who had been with us in this journey.

In the same year 1704, I went again into the province of Munster,
accompanied by Tobias Pim, and visited the meetings of Friends throughout that province;
the Lord opened to me the state of meetings where I came, to the comfort of many;
so returned home with joy.

In the year 1705,
there came a weighty concern upon my mind to go again to the yearly-meeting at London,
and to visit Friends`' meetings in some other parts of England,
under which exercise I greatly besought the Lord, and finding a necessity remain upon me,
I gave up to answer the Lord`'s blessed requirings; my dear wife being greatly helpful,
by encouraging me herein, as she had often been before, on the like occasions.
I acquainted our monthly-meeting, and also the half-year`'s meeting with my said concern,
who having unity therewith, Joseph Inman of Dublin accompanied me;
we took shipping from Dublin, after the half-year`'s meeting was over;
and in about twenty three hours landed at Nesson, so went to Chester, by land,
where we found the city in an uproar, about voting for parliament-men,
which brought great trouble upon me; but finding Friends were not concerned therein,
it gave me some ease.
From thence we went to Birmingham, and had a large and comfortable meeting,
where we met with Charles Floyd and his wife, whom I was glad to see;
we afterward met with Charles Osburn at Warwick, who accompanied us to London,
where we met with many Friends and brethren who were glad to see us;
and the Lord`'s heavenly power was greatly enjoyed in that yearly-meeting,
the hearts of Friends being in a tender frame.

When the said yearly-meeting ended, we parted with Friends in the sweet love of God;
and Samuel Waldenfield went with us to the quarterly and yearly-meeting at Colchester,
wherein the Lord`'s power eminently appeared, to the consolation of many;
we had also one meeting in our way thither;
Samuel Waldenfield returned from Colchester home, but Joseph and I went to Edmundsbury,
and had a meeting there, having visited several meetings in our way thither;
wherein the Lord`'s melting presence was felt, to the great comfort of Friends.
We went thence to the quarterly and yearly-meeting at York,
where was a large appearance of Friends; and the Lord greatly owned us,
both in the meeting for worship, and that for discipline and good order of the church;
which latter concern has been of great service to many.

We went from York to the monthly-meeting at Skipton,
visiting meetings in our way thither, and had several comfortable meetings there-away;
as also about Couln,
to many of which meetings we had the company of divers worthy Friends,
as William Ellis and his wife, John Ecrid, Laurence King, and several others;
Joseph and I went from thence to Sankey, so to Chester, and to Holyhead,
where we took shipping, and landed at Dublin,
having great peace from the Lord in answering his holy requirings,
and found our wives and children well.
Everlasting praises be given to the Lord,
who was pleased mercifully to favour us both in our going forth and return.

In this year 1705,
I had a concern to visit Friends`' meetings again in the province of Munster,
Henry Ridgway accompanied me; and after having visited all,
or most of Friends meetings in that province, and had many comfortable seasons,
we came to Waterford, and thence to Leinster province-meeting at Carlow,
where Friends were glad to see us, being mutually comforted,
in a living sense of the Lord`'s renewed goodness unto us.

In the year 1706,
I felt earnest drawings on my mind to visit Friends again in the province of Ulster,
in company with Charles Howel; we visited the meetings of Friends in that province,
and had good service for the Lord,
who gave us his word to publish and divide to the several states of Friends,
according as he was pleased to give us an understanding;
we were a strength one to another, as true yokefellows in the work; and in our return,
were made to rejoice in God, who had employed us in his service;
so parted one from another in great unity, and peace.

In the year 1707, I had drawings again to go into Ulster,
and dear William Watson had the like concern.
We visited the meetings of Friends in that province (as I had usually
done before) and the Lord eminently owned us in his work and service,
and Friends were greatly comforted in the Lord, and one in another.
We returned with great peace and satisfaction,
having the answer of "`well done`" in our bosoms; which was +++[+++a]
cause of thankfulness to the Lord, that was with us in our going out,
and near unto us in our return.

In the latter end of the year 1707,
I found a concern on my mind to go again into Munster, and William Watson went with me;
we visited all, or most of the meetings of Friends in that province,
to their and our great comfort and consolation.

In the year 1708 I went again into the province of Ulster,
in company with dear Thomas Wilson; we had many comfortable seasons with Friends there,
it being a time of great sickness, whereof many died suddenly,
and the minds of people were brought low;
so that our visit was both very seasonable and serviceable,
to the comforting and strengthening of many; but the weather being exceeding wet,
I was seized with great illness of body; yet the Lord supported me in his service,
so that I missed but one meeting in the province (which my companion
and others admired at) and returned home with great inward comfort,
though I did not fully recover my health until some months after.

In the year 1709, I had a concern upon my mind to go again into Munster-Province,
and met with William Dover at Dublin.
We first visited the meetings of Friends in the counties of Wicklow and Wexford,
and thence went to Waterford, so to Clonmel, where we met with Thomas Lightfoot,
who accompanied me through that province,
in which journey we had several heavenly meetings,
to the great satisfaction and comfort of Friends, and us also,
in performing our duty to the Lord and his people,
according to the understanding he was pleased to give us.

In the year 1710 I was under a renewed exercise and concern
of spirit to go to the yearly meeting at London,
in company with George Rooke, Joseph Pike, and several others;
and after the half-year`'s meeting at Dublin was over,
we took shipping thence and landed at Holyhead, and thence rode to Chester,
so to Birmingham, where we had a meeting; as also at Warwick,
and some other places in our way to London, and got there in due time,
to the yearly meeting, which held longer than usual,
many sensible concerned Friends being under great exercise,
and a zealous concern for the promotion of truth and keeping up the testimony thereof.

When the said yearly meeting was over, George Rooke,
and others of our company from Ireland, left Joseph Pike and me at London,
where we stayed three weeks; and then being clear, departed the city in peace of spirit;
and in our return homeward,
had a large and satisfactory meeting at Bugborough
(some Friends from Northampton being also there),
after which we parted with Friends in the love of God; so went to Chester,
and was at their meeting on the first day of the week; from thence to Holyhead,
and there took shipping and landed at Dublin,
where we parted in the sweet fellowship of the gospel;
and I returned home with great satisfaction in answering the Lord`'s requirings.

In the second month, 1711, I went again into Ulster, in company with John Chambers;
we visited all the meetings of Friends in that province,
and had many refreshing seasons with them; the Lord helped us,
and gave us his word in due season, which we published freely, so parted at Drogheda,
in a sweet sense of God`'s love flowing in our hearts,
wherein we were made dear to one another while he lived.
His death (being about three years after) was cause of sorrow to me and many more;
for he was a humble-spirited man, and well qualified for truth`'s service,
not valuing himself (as too many do) for human literature,
whereof he had a pretty large share.

In this year 1711, I found a concern on my mind to go to London again;
and our half-year`'s meeting being at Dublin in the ninth month; I went thither,
and being also appointed by that meeting, with several other Friends to attend at London;
to assist in soliciting the parliament there,
for an affirmation that might be easy to all Friends; it brought great exercise upon me,
considering the weight of the service, our own weakness, and the season of the year,
being in the deep of winter; yet believing the Lord required it,
and the church also desiring us, we gave up in faith.
And after our said half-year`'s meeting was over, Alexander Seaton, Nicholas Harris,
John Boles, Thomas Duckett, Gershon Boate and I,
took shipping at Dublin and landed at Holyhead, and thence rode to Chester,
and had meetings in our way at Wolverhampton and Dudley (some staying at Birmingham).
Gershon Boate and I went to Alcester, where my wife was born,
and several of her relations dwelt, and had a comfortable meeting with Friends there,
they being but seldom visited; and afterward we met the rest of our company at Coventry,
and had a precious meeting there that evening.
From thence we went to London where we found many country Friends,
and divers of the city,
with whom we joined (they being glad of our help) in preparing reasons,
and using endeavours with members of parliament,
etc. for an affirmation that might be generally easy to Friends;
in which service we continued there about six weeks, being often under great exercise;
yet the Lord was pleased frequently to appear,
and assist his servants in maintaining his testimony against opposers,
to the comfort and gladness of many sorrowful souls.
Praises be given to his great and glorious name forever.

Before I left London, I went to see the son and daughter of my cousin Daniel Barnard,
the son named Robert being put an apprentice,
and his sister Mary dwelling then in that city, I found her in a high dress;
but the Lord was pleased to humble and tender her heart by his mighty power,
so that she submitted thereto and kept constantly to Friends`' meetings,
and so became helpful to her brother, who was reached by the truth,
on which account he met with hardship from his master and family;
also after their return home to their parents, she was a strength to her said brother,
in taking up the cross; which so reached their father and mother,
that they were also convinced, he having been a Presbyterian,
and she a member of the Episcopal Church, and all reconciled in Jesus Christ,
which made my heart greatly rejoice, and praise the Lord,
who had wrought so eminently in them;
and I see my visits to them in the love of God were not in vain.

Being clear of London, we took our leave of Friends there, in the tender love of God,
many of whom expressed their good esteem of our labours of love amongst them;
so returned homeward in peace of conscience,
visiting only one meeting in the way at Forrest, near Chester;
and thence went to Holyhead, where we took shipping and landed at Bullock, near Dublin;
and I got well home, where Friends were glad to see me;
and we enjoyed the Lord`'s comfortable presence in our meetings.

In the year 1712, I went again into province of Munster,
in company with Thomas Lightfoot (and Moses Pim went with us).
We visited the meetings of Friends in that province as far as Castle-Salem,
and returned with peace in our bosoms.
Praises be given to the Lord, that leads out, and brings in again,
to the great comfort of them who follow his leadings.

In the year 1713,
I found my spirit under a concern to go again to the yearly meeting at London,
in company with Thomas Wilson, Jacob Fuller, William Watson,
and eight more Friends (appointed by the half-year`'s meeting:
we also met divers other Friends from Ireland at London,
being eighteen in all) and had an exercising time there; but as the Lord was waited for,
he was pleased to appear, for the help and comfort of his faithful travailing people.
This meeting was held by adjournment many days, and after it was over,
we took leave of Friends in the tender love of God.
I went thence in company with dear Thomas Aldam, towards Yorkshire,
and we parted at John Rhode`'s; from whence I went to Sheffield,
to my cousins Daniel Barnard and wife, etc. who were lately convinced;
and upon seeing each other, our hearts were mightily broken;
so that for some time we could say nothing,
but sat down (and tears of joy flowed from us);
after a while we spake one to another of the great love and mercy of God in Jesus Christ,
extended to them and their family, and in making me instrumental for their good,
the Lord having been pleased to turn them from darkness to the light of Christ,
in their own hearts, and call some of them as at the eleventh hour of their day.
Mary their daughter particularly expressed her having great benefit
by my former visit when she was but about twelve years old;
being seized often after with religious thoughts, and greatly desirous to see me again,
but a had not opportunity until that at London.

In the ninth or tenth month 1711 I stayed the meeting
at Sheffield one first day of the week,
wherein the Lord eminently appeared, and greatly tendered our hearts by his power,
affecting them with thankfulness unto him that lives forever and ever;
so took leave of my relations and Friends there in much tender affection,
except cousin Daniel Barnard, who set out, intending to accompany me as far as Chester;
I having appointed a meeting at Forrest near that city,
which being heard of by Patrick Henderson and William Gray,
they came from Chester to meet me,
so parted with cousin Daniel in great love and brokenness of spirit.
We went to Chester that night (after the said meeting)
where we met with more of our company,
and next day set out for Holyhead, from whence we had a ready passage to Dublin;
and I returned home, and found my wife and children well;
Friends also were glad of my return;
and my heart was deeply thankful to the Lord for all his mercies and preservations;
unto whom be praise forever, saith my soul.

In the eighth month 1713, I went again into the province of Ulster,
accompanied by Moses Pim, who, though he appeared not in a verbal testimony,
was a great help and strength to me, being a true travailer in spirit in meetings,
and greatly rejoiced when the Lord`'s power was in dominion.
We visited all the meetings of Friends in that province, having many good seasons;
and went a second time to Coothill, where a marriage was solemnized in the meeting,
to which many sober people came;
and the Lord`'s blessed power eminently appeared amongst us.
From thence we went to Dublin, to the half-year`'s meeting,
with great satisfaction and comfort.
Blessed be the Lord forever.

In the year 1714,
I being one nominated with other Friends to perform a visit to
the several monthly meetings throughout the province of Leinster;
some met at Dublin, and had many comfortable seasons with Friends in that city,
etc. but Jacob Fuller, Abel Strettel, and I went to Mountmellick, Birr, John Ashton`'s,
Cloncourse and Mountrath meetings, which service being over,
I went in company with Moses Pim, to Munster-Province Meeting, at Waterford,
where we had a comfortable time, and Friends were glad of that visit.
I thence returned home, and in a few months after went again into Munster,
accompanied by Mungo Bewley; we visited the meetings of Friends at Limerick, Charlevil,
Cork, Bandon, Skippereen and Castle-Salem, so back to Cork, and thence to Youghal;
in which meetings the Lord gave us his gospel to publish.
We went from Youghal to Clonmel,
where I received an account that my daughter Margaret was extreme ill,
not likely to recover, which brought great exercise upon me;
also Friends there were troubled thereat; and after advising with them I returned;
but my daughter departed this life a few hours before I got home;
yet my so coming was some comfort to my dear wife and children.

In the spring following I found a concern to go again into Munster, with my wife,
who also had the like concern to visit Friends there,
she having received a gift of the ministry.
We were at their Province-meeting in Cork,
and afterward had a meeting at each of the following places (viz.) Clonmel,
Joshua Fennel`'s house at Kilcommon, John Boles`'s and Cashel;
in all which meetings the Lord owned us with his presence,
and gave us his word to declare; so we returned home with great peace.

In the year 1715, I had a concern upon me to go to the yearly meeting at London,
so in company with Thomas Wilson, Joseph Pike, Thomas Pearce, Nicholas Harris,
Joseph Inman and three more Friends, being nine in all, we got well to London,
and after the service of the yearly meeting was over, finding myself clear of that city,
having fully answered, according to my understanding, what the Lord required of me,
I went thence in company of Joseph Inman and Joseph Storrs to Sheffield, in Yorkshire,
near where my cousin Daniel Barnard dwelt, where we stayed two days,
and had a precious time at their meeting,
several Friends from other meetings being there.
We had also a blessed season at cousin Daniel`'s house, so took leave of them;
but cousin Mary Barnard came with us, intending for Ireland.
We went by way of Chester to Holyhead, where we took shipping in the packetboat,
and landed at Dublin, from whence I returned home, and found my wife,
children and family well.
My heart was bowed with deep acknowledgments to the God of all our mercies,
who leads his forth, and accompanies them in their return.

In the year 1716,
I with my dear wife had drawings in our minds to visit Friends in the province of Ulster,
Joseph Medcalf and Thomas Pearson accompanied us.
We went to their province quarterly meeting at, or near Ballenderry,
where we met with John Danson from England; it was a comfortable time to many,
though some seemed too much settled down in a profession,
without the power and life of true religion.
We went from thence to Lisburn and had a meeting there; so to Lurgan, Monallen,
Ballyhagan, Charlemount, and back to Lurgan again, and thence to Cocthill,
Ballyhayes and Oldcastle,
after which meetings not finding any concern on our
minds to go further into the north at that time,
we returned home with peace.

In the year 1718, finding a concern,
and drawings of spirit upon me for some time to go again to the yearly meeting at London,
I gave up accordingly, and went in company with Joseph Gill, Robert Richardson,
and my cousin Tobias Pim.
We landed at Parkgate, from whence Joseph Gill went to Sankey,
but I with cousin Tobias went to Birmingham, and to Warwick, Worcester,
Oxford and Reading;
in most of which places we had good satisfaction with Friends in their meetings,
and thence to London, where we stayed until the yearly meeting was over,
and had blessed seasons, the Lord owning us in our service for him.
I then had a sense given me of a dreadful day of mortality coming upon the nations,
which I was concerned to publish at Devonshire House and some other places.
And when clear of that city; I went with my companion Tobias Pim towards Yorkshire,
in company with Joseph Storr of Chesterfield, and some others;
though as I went from London, I felt some drawings towards Lincolnshire;
and at Sheffield I saw clearly I must go back to Lincoln,
so took leave of my cousin Tobias,
and was accompanied by cousin John Barnard from Sheffield, thither,
and found but few Friends therein, which caused me to be greatly dejected that night;
but next day I met with Sarah Collier, and Friends from Brigs,
coming to their quarterly meeting at Lincoln, and one Henry Pickworth, an apostate,
being there, Friends were afraid he would be troublesome;
but the Lord`'s heavenly power broke in upon the meeting, and bound Pickworth, +++[+++so]
that he was very quiet.
We had a glorious time together, and parted in the tender love of God.

I went from Lincoln in company with Sarah Collier and other Friends to Gainsborough,
where we had a blessed meeting; after which we had two meetings at Brigg,
on first day of the week to our great satisfaction, and thence to the Isle of Axham,
and had a meeting there, where I parted with Brigg Friends in great tenderness,
and thankfulness to the Lord in the sense of his goodness.
I went from thence to Thorn, and to Selby, and had a meeting there;
and thence to the yearly meeting at York, where was a great appearance of Friends,
there being a very large meetinghouse built (and though not quite finished,
was very much thronged), and a comfortable season it was to many.
After which meeting, I went thence with that honourable elder Thomas Aldam, to his house,
and thence to Sheffield, not being yet clear of that place; but the next day,
being first day of the week, we had a very large and powerful meeting there;
so that I was then fully clear.

I went from Sheffield, accompanied by cousin Daniel Barnard to Henry Jackson`'s house,
where I had a meeting; and thence to Hallifax, so to Mankinholes,
where I got a sore fall from horseback, which disabled me from travelling for some time;
yet I got to a general meeting at Rossendale, which was very large,
where I met with dear John Haydock and John Ecrid; this was a good meeting,
truth being in dominion; blessed be the Lord forever.
From thence I went towards Forrest, and had a meeting there;
after which I went to Chester that night,
where I met with two worthy women (Sarah Elam and Katharine
Storr) intending to visit Friends`' meetings in Ireland.
We set forward towards Holyhead, and in three days got thither,
where we took shipping and had a good passage to Dublin.
From whence I went home, and found my dear wife, children and family all well.
Blessed be the Lord, whose mercies are great to them that serve him uprightly.

In the said year 1718,
I went with George Rooke to visit Friends`' meetings in Ulster Province,
being accompanied by other three Friends of Dublin,
to several meetings (viz.) my uncle Samuel Baker, Abel Strettell, and Timothy Forbes.
We had a precious meeting at Rathfryland, where many people came in.
We also had a meeting at Lisburn, likewise at Ballenderry and Lurgan;
as also opportunities with the members of mens meetings to excite
them to an holy zeal in keeping up good order and discipline,
enquiring how they had observed the many wholesome minutes given
forth for the good of all who profess the truth amongst us;
in which concern the said three Friends were helpful.
So leaving George and me at Lurgan, they returned homeward; but we two went on to Antrim,
and had a meeting there, but found things not to our satisfaction; as also at Grange,
where we perceived a great decay of zeal.
We had next a public meeting at James Moore`'s house, as also a seasonable time after it,
with the members of men and women`'s meetings together, and came away easy.

We went from James Moore`'s to Toberhead, and had a comfortable meeting there;
likewise at Charlemount and Ballyhagan,
their mens and women`'s meetings having been appointed to be held when we were there;
it proved greatly to our satisfaction.
We went thence to the province-meeting at Coothill,
where was a great appearance of Friends and other people.
We had a good season, the Lord`'s heavenly power being eminently manifested,
to the comfort of many.
Here we parted, George returned homeward, but I went to a meeting at Oldcastle,
which was a confirming meeting to me that the Lord owned me in his service.

In the year 1720, at Dublin, in obedience to the Lord,
I was concerned the give forth the following lines, being,

[.embedded-content-document.epistle]
--

[.centered]
=== A Faithful Warning

[.blurb]
=== To the Inhabitants of Great Britain and Ireland, to Dread the Lord, and Turn From Their Evil Doings Before His Fury Break Forth Upon Them, as an Over-flowing Scourge.

The Almighty God of heaven and earth hath long strove with these nations in mercy and
lovingkindness in order to reclaim us from those evils which greatly abound therein;
but instead of being humbled by his manifold mercies plentifully bestowed upon us,
many have exalted themselves, under a profession of Christianity, and forgot the Lord;
having a name to live, but wanting true life and rest to their souls.
Also too many of the teachers,
have both by example and doctrine indulged them in a liberty pleasing to the flesh,
whereby the strait gate and narrow way, spoken of by our blessed Saviour, Matt. 7:13,
and his cross, mentioned by the apostle Paul, Gal. 6:14,
which crucifies to the world, have been much neglected,
and the broad way which leads to destruction and eternal misery,
walked pleasantly in by many.
And so the fruits of Christianity in life and conversation have been,
and are greatly wanting.
I could say more upon this subject,
but am willing only in brevity to clear my conscience in the sight of God.

In the year 1688, a dark cloud appeared over the nations, and the sword threatened,
which also fell heavy on some parts of Europe;
but the Lord was pleased to spare the nation of England,
which should have caused her inhabitants to be greatly
humbled and bowed in thankfulness unto him,
the Lord God of heaven and earth,
who gives and changes the kingdoms of men as he pleaseth.
And ye have had a long space to repent and amend your ways,
but have not laid it to heart to give glory to God, who hath been so gracious unto you;
but instead of bearing the mark of true Christians in meekness and love one to another,
a bitter spirit of hatred and pride hath predominated,
which hath highly provoked the Lord to anger;
so that his wrath is great against thy inhabitants, Oh England! to be speedily executed,
if there be not repentance and amendment of your ways and doings.
For I being at London in the year 1718, was then made fully sensible,
that the destroying angel of the Lord was nigh to execute judgment upon thine inhabitants,
and particularly that great city of London.

And now also I find a concern upon my heart unto the inhabitants
of this nation of Ireland wherein I dwell,
to put them in remembrance of the Lord`'s providences unto us,
who were sensible of the destruction by fire and sword,
mostly in the years 1689 and 1690, whereby in divers places,
many houses and stately buildings were laid in ashes; the young men slain with the sword,
and the mighty fell in battle.

But O! then the Protestants of all denominations were humbled before the Lord,
and so united in love and affection one to another,
that I did not think of living to see so much hatred and bitterness
as since hath been and yet continues amongst them,
which hath been, and is the cause of deep sorrow to my soul in secret before the Lord,
being often seized with great fear and terror concerning
what is like to be the event thereof,
unto those who have seen and forgotten such great
and eminent providences and deliverances of the Lord;
and broken the solemn promises and covenants, which I doubt not many have entered into,
with the Most High: that if he would graciously spare, and be merciful unto them,
they would break off their sins by repentance,
and serve him according to the gift of his grace bestowed upon them: but on the contrary,
+++[+++these]
rush into pride, idleness, covetousness, oppression, hatred, lying, and hypocrisy,
and those crying sins that greatly abound in the nation, as profane swearing, cursing,
drunkenness, and debauchery, (against which there have been good and wholesome laws made,
were they duly executed), so that now the measure of the sins of many seem to be full,
and therefore I believe the Lord will surely visit speedily,
with a great and heavy scourge, if not prevented by repentance.

And further, when the late rebellion and war brake forth in Great Britain,
threatening desolation; Oh! what fears surprized many, both there and here,
concerning the event thereof.
And I believe the Lord heard the strong cries, and humble petitions of such,
who (like King David, having seen the destruction of war) besought the Most High,
that we might fall into his merciful hands,
rather than into the hands of unreasonable men.
And behold!
He was graciously pleased, in an eminent manner, to call back the sword,
and disappoint those, who seemed likely to have been the rod of his wrath.

And now, we have heard that the plague rages in some parts of France,
whereby many thousands have been suddenly taken away,
and yet the report thereof seems not to humble us, so deeply as we ought;
for which cause, at times my soul hath been exceedingly sorrowful,
and afflicted night and day: the Lord having been pleased to shew me,
that the stroke of mortality is near at hand.
And whereas his mercies and gentle dealings have not humbled the nations,
his judgments will be terrible to the workers of iniquity,
and I see no way to divert the impending judgments of an offended God,
but such fasting as the Lord spake of by his prophet Isaiah, chap.
58 vers.
6-7, "`Is not this the fast that I have chosen, to loose the bands of wickedness,
to undo the heavy burdens, and to let the oppressed go free:
and that ye break every yoke.
Is it not to deal thy bread to the hungry?
and that thou bring the poor that are cast out, to thy house?
When thou seest the naked, that thou cover him?
and that thou hide not thy self from thine own flesh?`"
And crying mightily unto God, as the Ninevites did, Jonah 3:8,
from the king to the meanest of his subjects,
and if all turn from the evil of their ways,
I have some hope the Lord`'s anger may thereby be appeased,
and our tranquillity lengthened, and am persuaded as the apostle declared,
Acts 10:34-35, that "`In every nation, he that feareth God, and worketh righteousness,
is accepted of him,`" and that it will be well with them.

[.centered]
=== To the People Called Quakers

[.salutation]
Dear Friends and Brethren,

I have been in deep affliction of soul and spirit before the Lord,
because of his judgments, that are like to break forth speedily,
if there be not great humiliation,
and imploring him to grant unto the nations a little longer time of mercy;
for we (as well as others) have been too deeply concerned
in offending our gracious and long-suffering God.
Wherefore I fervently entreat and beseech you everywhere to lay it to heart.
And that as the Lord hath been pleased to reveal and make
known his light and truth unto us in our hearts;
we may be obedient thereunto in a self-denying life, as the followers of Jesus,
according to our holy profession; but too many,
not having practised what they have known to be their duty, have greatly afflicted many,
both in this nation and elsewhere.

And my friends, the Lord hath not only often reproved us by his Holy Spirit,
and grace in our own hearts, in order that we should turn from every evil way;
but also hath raised up, and concerned his servants,
to call unto all under our profession for humiliation,
and to let our moderation appear unto all men,
as the apostle advised the primitive Christians, for the Lord is at hand.
He hath also raised up prophets amongst us, who have foretold of the late wars,
before they came to pass, and others since,
to give notice of a great mortality approaching,
with warning to prepare to meet the Lord, in the way of his righteous judgments,
and flee the evil and entanglements of this world.
But oh! how many have grown high-minded,
and sat down at ease in their outward enjoyments, and others made haste to be rich,
whereby they have fallen "`into temptation and a snare,
and into many foolish and hurtful lusts,
which drown men in destruction and perdition,`" 1 Tim. 6:9. So that I may say,
too many have been as the deaf adder that will not hear;
wherefore I am also now to warn you my dear Friends, to prepare to meet the Lord our God,
for his anger burns hot, and he hath shewed me in his light,
that he is about to bring a terrible day upon these nations,
because they have rejected his reproof; and turned his law behind their backs.
And I see nothing that will appease his wrath, but true humiliation and fasting,
with strong and fervent cries unto him.
I am also persuaded the stroke of mortality might have been given before now,
had not the sincere cries of many (to stay his hand) prevailed with him,
that lives forever and ever.

And dear Friends,
I would have us of this nation retain a thankful remembrance
of the great and eminent deliverances of the Lord,
wrought for us, insomuch that very few of us fell in time of the said war,
but were supported through many difficulties,
though we diligently kept up our meetings for the worship of Almighty God,
often in peril of our lives: under an humble sense whereof,
at our next ensuing national meeting,
our hearts were filled with thanksgiving and our eyes with tears of joy.

And whereas the prophet Ezekiel in the vision concerning Jerusalem,
saw one sent with a writer`'s inkhorn by his side to put a mark upon such,
as sighed and cried for the abominations, that were committed,
so now such will be happy in that day, come life or death.
And after this cloud shall pass over,
the Lord will raise up and send many ministers of his word of life,
to publish the gospel of peace and salvation unto the nations abroad, to the hazard,
or laying down of their lives for the testimony of Jesus.

These things have been hard for me to write, knowing it may meet with many censures;
but the word of the Lord burnt as a fire, in me, that I could not be silent,
nor find ease, until I gave up thereunto.
So leaving the issue to the Lord, desiring it may have a good effect: I subscribe,
as I am, a lover of the souls of all men,

[.signed-section-signature]
John Barcroft.

[.signed-section-context-close]
Dublin, 13th of 9th Month, 1720.

--
