[quote.epigraph, , Prov. 10:7]
____
The memory of the just is blessed.
____

[quote.epigraph, , Rev. 14:13]
____
Write, blessed are the dead which die in the Lord, from now on: Yes, says the Spirit,
that they may rest from their labours, and their works do follow them.
____

== Preface

[.salutation]
Candid Reader,

There being sundry faithful testimonies hereafter concerning
the qualifications and services of this our dear friend,
I shall here only hint briefly of them.

He was a prepared vessel and qualified instrument for the
Lord`'s use and service sanctified by the power of God,
and operation of the word of truth in his heart, and inward parts,
having experienced the spiritual-baptism and new-birth,
and growing up to the state of a man in Christ, became skillful in the things of God.
First, as a helpmate in government and discipline,
wherein he was very diligent aid serviceable, being zealous for the honour of God,
and welfare of the churches, and himself a good example, ruling well his own house,
and grieved when any professing the Holy Truth,
brought dishonour thereon by walking contrary; and,
though sometimes sharp in reproof to such, yet he was tender when suitable,
as the nature of the faults and offences differed, or persons concerned were penitent,
with earnest desire of their restoration.

In or about the thirty-third year of his age,
it pleased God to call him into the ministry of the word and doctrine,
which for a time seemed hard to him to give up unto,
but the power and love of Christ prevailing made him willing to obey,
so that he became a faithful labourer in the gospel of peace and salvation,
and travelled much, visiting Friends`' meetings in this nation of Ireland,
as also often in various parts of Great Britain,
having been ten times at the yearly-meeting at London,
and once in that city at another time, in the winter season, on truth`'s account;
for as he was not slothful in his outward necessary affairs,
but managed them with discretion and prudence, he was fervent in spirit,
serving the Lord and his people, preferring the prosperity of Zion, as his chiefest joy.

He was very temperate in living, plain and decent in habit,
etc. and in conduct pleasant and cheerful, yet grave, meek, and humble,
preferring others before himself; a peace-maker, and follower after holiness,
a fervent lover of the brethren, and unity among them,
a frequent visiter of the sick and afflicted,
freely ministering relief to the poor and indigent,
(he having some skill in medicine and surgery) kind and generous in entertaining Friends,
and strangers, charitable towards all,
thus bearing the marks of a true disciple of the Lord Jesus Christ;
and as to his Christian duty in his own particular family,
I think few (if any) exceeded him in love and tenderness as a husband,
in care and affection as a father, or in gentleness and equity as a master.

About three years before his death,
he gave forth a warning to the inhabitants of Great Britain and Ireland unto repentance,
declaring the Lord was provoked to anger, by the abounding of sin,
and would therefore visit with his judgments, if the people be not humbled, and repent.
Which warning coming forth about the time of our national half-year`'s meeting,
a large number was printed and spread, both among Friends and others,
for a general service in this nation, and some sent to Great Britain.

Lastly, it may be observed by a short introduction of the author,
that the service of his ensuing journal was chiefly (if not only)
intended for the information and comfort of his children;
but Friends having had good unity with his Christian labours in his time,
esteem the account he has left thereof worthy to
be published in print for a general service,
with an earnest desire that not only his offspring and outward relations,
and those that knew him, but likewise all who shall read his journal, etc. may,
(according to the measure of grace received) endeavour to follow his pious example;
and when this mortal life is ended, obtain life everlasting,
which (I doubt not) this our dear Friend is entered into,
enjoying the reward of his labours.

Written by a friend and lover of his memory (that knew him
many years) wishing salvation to mankind universally.

[.signed-section-signature]
John Stoddart
