== Postscript

[.centered]
=== Some Addition by Way of Supplement To the Journal of Our Worthy Friend John Barcroft.

In the perusing the journal of our worthy Friend John Barcroft, deceased;
which appears in his own handwriting, and carried on until the year 1718,
in which year he visited Friends in the province of Ulster;
and making a period or full stop on giving account of his being at a meeting at Oldcastle,
which being in his way home, we conclude he came directly home from there,
and in his usual manner frequently attended not only the meeting for worship,
to which he did belong, in which he was a good example: but also when of ability of body,
diligently attended both monthly province, and national meetings,
for the management of the good order and discipline of the church,
for which he was gifted beyond many, and serviceable therein;
he was also very helpful in ending and composing of differences that have happened,
both among Friends and others.

It is also very observable,
that besides the care and concern that was upon him
for the peace and prosperity of the church,
he was deeply affected with a sense of some approaching calamity,
as a scourge from the Almighty;
and therefore several times was concerned to warn Friends in their meetings,
to prepare for a trying time, which seemed to him to be very terrible.
Under which concern he often put Friends in mind of the
calamity which attended the late revolution in this kingdom,
and the wonderful deliverance which the Lord wrought for his people,
who trusted in his delivering arm; about which time of his exercise,
he wrote and published the foregoing short prophetic
warning to the inhabitants of Great Britain,
and Ireland, in the year 1720, which was approved among Friends;
and which we believe would have been fulfilled before this, if the long-suffering of God,
did not far exceed the humiliation of the children of men.

Also in the same year he had a concern upon his mind to
visit the meetings of Friends in the province of Ulster;
which he accordingly accomplished, to the satisfaction and comfort of Friends,
and his own peace.

We also find by several of his letters, bearing date from London and Bristol,
in the year 1721, that he went to the yearly meeting at London,
in company with our worthy friend Thomas Wilson, and other Friends,
and had a meeting as they went at Wolverhampton,
and was at the burial of John Peaton`'s wife at Dudley; and afterwards to Broomsgrove,
to the quarterly meeting for Worcestershire, and so passed on to London,
having several other satisfactory meetings as they went, and stayed the yearly meeting;
and then went to Bath and Bristol, where he had a sore fit of sickness,
which illness occasioned him and his dear friend Thomas Wilson to part.
But it pleased the Lord to raise him up again, who when a little recovered,
returned homeward, as soon as his weak condition would admit,
and through providence got home to his house,
where his family and friends were very glad to see him;
and at times he expressed the satisfaction he had in that journey,
and particularly in the time of his illness while at Bristol,
where he was freely given up to die,
being well satisfied that his peace was made with the Lord,
whose refreshing presence he was a partaker of, in a particular manner,
in the time of his sickness.

After his return from England as aforesaid, being pretty well recovered,
he attended meetings in our own province, and in the year 1722,
found a concern and drawings on his mind to visit
the meetings of Friends in the province of Munster,
which he did pretty generally; his visit was not only acceptable to Friends there,
but much to his own satisfaction, and he returned to his house in peace.

After this journey being mindful of settling the affairs of his family,
in order to leave those of his household after him in peace,
he made provision accordingly, in case of his removal by death.

We do not find by any account come to our view,
that he travelled any more in either of the provinces of Ulster and Munster,
growing feeble, and often unwell, yet continued attending monthly and province meetings,
when of ability of body;
and even to the last diligently attended the particular
meeting (for worship) to which he belonged,
where his example and service is much missed; and though he is removed from this life,
no doubt his spirit lives among the righteous in the kingdom of eternal joy,
and his memory still remains sweet to a surviving remnant.

[.centered]
=== Testimonies Concerning John Barcroft

[.blurb]
=== A Testimony Given Forth by Friends of the National Meeting in Ireland, Concerning our Dear Friend John Barcroft, Deceased.

He was son of Willian and Margaret Barcroft,
born near Rosenallies in the Queen`'s-County, about the year 1663,
and was educated in the way of truth by his parents;
and when young was religiously inclined, being a constant comer to meetings,
and a diligent waiter therein, and grew in the knowledge of God,
and mysteries of his heavenly kingdom.

He was a great sufferer in the common calamity in the time of the late war,
and was one of the first Friends who came to reside near Edenderry after the wars;
to which meeting he did belong,
and was very helpful at that time to encourage some few families,
to meet together to worship God, and became very serviceable in the said meeting,
which is since become large.

About the thirty-third year of his age,
the Lord was pleased to endue him with a gift in the ministry; and growing therein,
he approved himself a faithful labourer,
and often visited the meetings of Friends in this nation,
as also in several parts of England,
and particularly that of attending the service of the yearly-meeting in London.

It may be truly said he was given up in body and substance to serve the Lord,
his church and people, and was a preacher of righteousness,
not only in word and doctrine, but in life and conduct.
His ministry was plain and living, not forward in appearing, but when he had a necessity;
and when so concerned it was both seasonable and suitable,
and to the comfort and encouragement of Zion`'s mourners.
Much might be said concerning him, which for brevity`'s sake is omitted.
He was taken off by a short sickness, his distemper being heavy upon him,
which he bore patiently.

He quietly departed this life the 24th of the eleventh month, 1723; aged about 60 years,
and a minister about 27 years; and thought our loss be great,
we doubt not it`'s his great gain.

Signed on behalf of the said meeting, held in Dublin, the 9th of the Third month, 1724,
by

[.signed-section-signature]
Thomas Duckett, George Rooke, William Brookfield, Jacob Fuller, John Stoddart,
Thomas Wight, John Stevens, Richard Sealey, William Gray, John Wily, Robert Richardson,
Joseph Inman, Bartholomew Garnett, Nicholas Harris, Ralph Stephenson, Joseph Gill,
Richard Mercer, Abel Strettell, Daniel Bewly, Samuel Fuller.

[.blurb]
=== A Testimony given forth by Friends of Mountmellick Men`'s Meeting, concerning our dear Friend John Barcroft, deceased, son of William and Margaret Barcroft, who was born near Rosenallies in the Queen`'s-County, about the year 1663, and was a member of Edenderry-Meeting for many years.

He was educated in the way of truth by his parents; and,
when but a youth was a constant comer to meetings, and a diligent waiter therein;
wherein he grew in the knowledge of God, and in the mysteries of his heavenly kingdom;
his circumspect conduct among men greatly adorned his profession;
he was a great sufferer in the common calamity in the time of the late war,
and was the first Friend who came after the war to settle near Edenderry,
and was very helpful to encourage some few families in meeting together to worship God,
(several of us have known him above forty years)
and about the thirty-third year of his life,
the Lord was pleased to call him to be a minister of the gospel,
in which he faithfully laboured in the work thereof,
and often visited the meetings of Friends in this nation;
as also in several parts of England,
and has been several times at the yearly meeting at London.

It may be truly said he was freely given up in body and substance to serve the Lord,
his church and people; he did not only preach in word and doctrine,
but also in life and conduct; he had a living ministry,
being often drawn forth for the comfort and encouragement of Zion`'s mourners.

He was concerned for the good of the church, and very helpful in the discipline thereof,
his service is much missed among us,
(especially in the meeting to which he did belong)
where his memory lives in the hearts of many,
with sweetness; he greatly laboured for love and unity among Friends,
but when his labour had not its desired effect, it was great grief and trouble to him.

He was ready and willing to visit Friends both rich and poor, when in affliction,
either of body or spirit,
and was often drawn forth in supplication to the Lord for the young generation,
a man greatly beloved by his friends and neighbours,
and has left a good savour behind him.

He was endowed with a good understanding in natural things,
and was very helpful to many by advice and otherwise, both in medicine and surgery,
which he did freely, without money.
Much might be said concerning him.

He was taken off with a short sickness, his distemper being heavy upon him,
which he bore patiently, did not speak much,
yet a little before his departure he said his time was shortening fast,
and desired those about him to be still,
who quietly departed this life the 24th of the eleventh month, 1723,
and though our loss be great, yet we believe it is his great gain.

He died aged about sixty years, a minister twenty-seven years;
he was decently buried in Friends burying-place near
Edenderry on the 27th of the same month,
his corpse being accompanied by many Friends from several parts of the province,
and other friendly people who were his neighbours,
where testimonies were born to the truth.
Signed on behalf of said men`'s meeting,
held at Montrath the 12th day of the second month, 1724, by

[.signed-section-signature]
Thomas Pim, Ralph Stephenson, Daniel Huson, Samuel Watson, Daniel Barnard, Tobias Pim,
Joseph Medcalfe, Mungo Bewley, Eliezar Sheldon, George Roberts, John Pim,
Joshua Strangmax, Joshua Pim, Sam.
Watson, of Kill, Thomas Atkinson, Jacob Cantrell, Archibald Nevins, James Hutchinson,
Henry Lingwood, Thomas Pearson, Samuel Pearson, Ephraim Heritage, William Nevill,
Humphry Barnes

[.blurb]
=== Elizabeth Barcroft`'s Testimony, Concerning Her Husband John Barcroft, Deceased

[.signed-section-context-open]
Dated the 6th of the Third Month, 1724.

It is in my mind to write something concerning my dear husband John Barcroft, deceased:

He was religiously inclined from a youth,
and after it pleased the Lord to join us in marriage, he grew in the blessed truth;
and after some time it pleased the Lord to endue him with a gift in the ministry,
in which he was concerned to discharge his duty faithfully.
He was also gifted in discipline in the church, which he managed in the ability of truth;
and I may say when he found a concern upon his mind to travel abroad,
in the service of truth, he thought nothing too near to part with for truth`'s sake,
and was a diligent labourer in his day for the good of souls,
and the Lord prospered the work in his hand; and while ability of body was continued,
he spared not himself, but often desired to do his day`'s work in his day,
not desiring long life in this world;
and when weakness of body attended him that he could not travel as formerly,
a concern lay upon him, that those that had ability of body, and were gifted men,
might do their day`'s work while they had time,
for the carrying on that great work of reformation, that the Lord had begun in the earth;
and as he was faithful in the service of truth,
he also earnestly desired the peace of the church, and laboured as much as in him lay,
according to the ability given him, to reconcile differences that did arise,
either among his friends or neighbours,
and was concerned that they might be ended according to justice and equity,
he desiring the good of all men.

I may say of him that he was a loving, tender husband,
and an affectionate father to his children, often giving them good advice,
and was concerned for them many times in prayer,
and also for the offspring of Friends in general,
that they might be brought to the knowledge of the blessed truth;
he was a man of a good example in his family, and among his neighbours,
being of a steady conduct.
He was pitying to the poor, and constantly kept to meetings when in health of body;
he was a sympathizer with the afflicted, and a true Friend.
His removal was something sudden unto us; yet in the time of his illness,
he lay in a sweet composed frame of mind,
and though it be my great loss to lose so dear a companion,
I do believe it is his great gain, to be dissolved and be with Christ his redeemer.
He departed this life the 24th of the eleventh month 1723, like one falling asleep:
he was sensible to the last;
and I am well satisfied is entered into rest and peace with the Lord,
where the wicked cease from troubling, and the weary are at rest.

[.signed-section-signature]
Elizabeth Barcroft

[.signed-section-context-close]
Ballytore the 6th of the Third Month, 1724.
